### PR TITLE
Remove gackground when sending only emojis

### LINKED ISSUE #2: Background showing up when sending only Emojis
Default theme:
image

Dracula theme:
image

As you can see, the background of the emojis is not being omitted.

### PR DESCRIPTION
**Pull request by marsavela**
Before:
image

After:
image

Fixes #2

### CODE REVIEW

**Comment by marsavela** [comment]
Forgot to ping @ppartarr 

Thinking about this, maybe this is not the best approach. Maybe I should check why it get's the background in the first place instead of just removing it once it's set... I will check it if I have time.

**Comment by ppartarr** [comment]
Hey @marsavela, I'll make a couple more changes today and tomorrow and update the app on the chrome web store so your changes can go live 😄

**Comment by marsavela** [comment]
@ppartarr I've seen some other bugs as well. If I have some time, probably I will take a look and try to push a couple.of PRs. I am in a business trip right now, so my schedule is a little bit tight. 😞

**Comment by ppartarr** [comment]
Sure. Feel free to create issues to document the bugs!

**Pull request merged**
