### PR TITLE
Fix Status icon color

### PR DESCRIPTION
**Pull request by marsavela**
### Before
image
_Note: the status icons should be displayed with the grey color_
### After
image

### CODE REVIEW

**Comment by marsavela** [comment]
@ppartarr Please review.

**Comment by marsavela** [comment]
Fixes #8

**Comment by ppartarr** [comment]
Thanks for pointing these out @marsavela (#9 #10)!

The theme is becoming a bit too much like a "dark mode" rather than a dracula theme so I'm going to start using the brighter colours available in the palette (https://github.com/dracula/dracula-theme).

I'll merge these asap and update the app on the chrome store before the end of this week

**Comment by ppartarr** [comment]
@marsavela I'm going to close this since the re-skin uses this "messenger blue" colour quite a bit. 

It isn't in the dracula colour palette but is the default SVG colour for icons in the "Conversation information" tab on the right hand side (see below)

icons

**Pull request closed without merging**
